import { ThemeComponents } from '@/types';
import {
    MuiAutocomplete,
    MuiButton,
    MuiCard,
    MuiCheckbox,
    MuiChip,
    MuiFab,
    MuiPaper,
    MuiPopover,
    MuiRadio,
    MuiSelect,
    MuiSlider,
    MuiSwitch,
    MuiTable,
    MuiTextField,
    MuiToggleButton,
    MuiToggleButtonGroup,
    MuiTypography,
    MuiTooltip,
    MuiBackdrop,
    MuiDialog,
    MuiLinearProgress,
    MuiSkeleton,
    MuiSnackbarContent,
} from './theme-components';

const themeComponents: ThemeComponents = {
    MuiPaper,
    MuiAutocomplete,
    MuiButton,
    MuiCheckbox,
    MuiCard,
    MuiTextField,
    MuiFab,
    MuiRadio,
    MuiSelect,
    MuiPopover,
    MuiTypography,
    MuiSlider,
    MuiSwitch,
    MuiToggleButton,
    MuiToggleButtonGroup,
    MuiChip,
    MuiTable,
    MuiTooltip,
    MuiBackdrop,
    MuiDialog,
    MuiLinearProgress,
    MuiSkeleton,
    MuiSnackbarContent,
};

export default themeComponents;
