import { ThemeComponents } from '@/types';
import {
    MuiAccordion,
    MuiAppBar,
    MuiAutocomplete,
    MuiBackdrop,
    MuiButton,
    MuiCard,
    MuiCheckbox,
    MuiChip,
    MuiDialog,
    MuiDrawer,
    MuiFab,
    MuiLinearProgress,
    MuiMenu,
    MuiPagination,
    MuiPopover,
    MuiRadio,
    MuiSelect,
    MuiSkeleton,
    MuiSlider,
    MuiSnackbarContent,
    MuiStepper,
    MuiSwitch,
    MuiTable,
    MuiTextField,
    MuiToggleButton,
    MuiToggleButtonGroup,
    MuiTooltip,
    MuiTypography,
    MuiTabs,
    MuiList,
} from './theme-components';

const themeComponents: ThemeComponents = {
    MuiAutocomplete,
    MuiButton,
    MuiCheckbox,
    MuiCard,
    MuiTextField,
    MuiFab,
    MuiRadio,
    MuiSelect,
    MuiPopover,
    MuiTypography,
    MuiSlider,
    MuiSwitch,
    MuiToggleButton,
    MuiToggleButtonGroup,
    MuiChip,
    MuiTable,
    MuiTooltip,
    MuiBackdrop,
    MuiDialog,
    MuiLinearProgress,
    MuiSkeleton,
    MuiSnackbarContent,
    MuiAccordion,
    MuiAppBar,
    MuiDrawer,
    MuiMenu,
    MuiPagination,
    MuiStepper,
    MuiTabs,
    MuiList,
};

export default themeComponents;
